---
title: "flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
```

```{r}
h1b_2018 = read.csv(file = "./data/dataset.csv")  
## this is a test to read and open the dataset
## I created a folder in our project called "data" 

## then inside it I downloaded the dataset and called it "dataset.csv" 

## then inside it I downloaded the dataset and called it "dataset.csv"


####select the 16 variables which we are interested in
h1b_18_filter = h1b_2018 %>% 
  janitor::clean_names() %>% 
  select(case_number, visa_class, case_status, employer_name, employer_country, employer_city, employer_state,
         naics_code, soc_code, soc_name, total_workers, employment_start_date, employment_end_date, full_time_position,
         prevailing_wage, pw_unit_of_pay, worksite_city, worksite_state, h1b_dependent) %>%
  filter(case_status == "CERTIFIED",
          visa_class == "H-1B",
          employer_country == "UNITED STATES OF AMERICA") %>% 
  select(-visa_class, -case_status, -employer_country)

```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Map showing number of H1b in employer state

```{r}
state_number = 
  h1b_2018 %>%
  group_by(employer_state) %>%
  summarize(n = n())

state_number$hover <- with(state_number, paste("State", employer_state, "<br>", "Number", n))

g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

map_1 <- plot_geo(state_number, locationmode = 'USA-states') %>%
  add_trace(
    z = ~n, text = ~hover, locations = ~employer_state,
    color = ~n, colors = 'Purples'
  ) %>%
  colorbar(title = "H1b Case Number") %>%
  layout(
    title = '2018 US H1b by State',
    geo = g
  )

map_1
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B:Map showing number of H1b in worksite state

```{r}
state_ws = 
  h1b_2018 %>%
  group_by(worksite_state) %>%
  summarize(n = n())

state_ws$hover <- with(state_ws, paste("State", worksite_state, "<br>", "Number", n))

g2 <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

map_2 <- plot_geo(state_ws, locationmode = 'USA-states') %>%
  add_trace(
    z = ~n, text = ~hover, locations = ~worksite_state,
    color = ~n, colors = 'Greens'
  ) %>%
  colorbar(title = "H1b Case Number") %>%
  layout(
    title = '2018 US H1b by worksite State',
    geo = g2
  )

map_2
```


 
### Chart C: Graph showing top 10 cities with H1b cases in California state (worksite)

```{r}
city_ca = 
  h1b_2018 %>%
  filter(worksite_state == 'CA') %>% 
  group_by(worksite_city) %>%
  summarize(n = n()) %>% 
  filter(min_rank(desc(n)) <= 10)

city_ca %>% 
  mutate(worksite_city = fct_reorder(worksite_city, n)) %>% 
  plot_ly(x = ~worksite_city, y = ~n, color = ~worksite_city, type = "bar")
```


### Chart D: 
```{r}
h1b_location =
  h1b_18_filter %>% 
  select(case_number, employer_city, employer_state, worksite_city, worksite_state) 

h1b_employer_50 = h1b_location %>% 
  filter(!employer_state %in% c("DC", "GU", "MP", "PR", "VI")) %>% 
  group_by(employer_state) %>% 
  summarize(employer_number = n()) %>% 
  rename("state" = "employer_state")

h1b_worksite_50 = h1b_location %>% 
  filter(!worksite_state %in% c("DC", "GU", "MH",  "MP", "PR", "VI")) %>% 
  group_by(worksite_state) %>% 
  summarize(worksite_number = n()) %>% 
  rename("state" = "worksite_state")


h1b_location_data_big = 
  full_join(h1b_employer_50, h1b_worksite_50, by = "state") %>% 
  filter(worksite_number >= 2000 | employer_number >= 2000) 
  
h1b_location_data_small =
  full_join(h1b_employer_50, h1b_worksite_50, by = "state") %>% 
  filter(worksite_number < 2000 & employer_number < 2000) %>% 
  mutate(employer_number = sum(employer_number),
         worksite_number = sum(worksite_number)) %>% 
  mutate(state = "Others") %>% 
  select(state, employer_number, worksite_number) 

others = unique(h1b_location_data_small) 

h1b_location_data = 
  bind_rows(h1b_location_data_big , others)
  

h1b_location_data %>% 
  mutate(state = fct_reorder(state, worksite_number)) %>% 
  plot_ly(x = ~state, y = ~employer_number, type = 'bar', name = 'headquater location') %>% 
  add_trace(y = ~worksite_number, name = 'work location') %>%
  layout(yaxis = list(title = 'Count'), barmode = 'group', legend = list(x = 0.1, y = 0.9))

  


```

```{r}
rmarkdown::render("flexdashboard.Rmd", output_format = "flexdashboard::flex_dashboard")
```
