---
title: "Untitled"
author: "Katie Gao"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
```

TEST 123
testing 

```{r}
h1b_2018 = read.csv(file = "./data/dataset.csv")  
## this is a test to read and open the dataset
## I created a folder in our project called "data" 

## then inside it I downloaded the dataset and called it "dataset.csv" 

## then inside it I downloaded the dataset and called it "dataset.csv"


####select the 16 variables which we are interested in
h1b_18_filter = h1b_2018 %>% 
  janitor::clean_names() %>% 
  select(case_number, visa_class, case_status, employer_name, employer_country, employer_city, employer_state,
         naics_code, soc_code, soc_name, total_workers, employment_start_date, employment_end_date, full_time_position,
         prevailing_wage, pw_unit_of_pay, worksite_city, worksite_state, h1b_dependent) %>%
  filter(case_status == "CERTIFIED",
          visa_class == "H-1B",
          employer_country == "UNITED STATES OF AMERICA") %>% 
  select(-visa_class, -case_status, -employer_country)

```

## A map showing number of H1b in employer state

```{r}
state_number = 
  h1b_2018 %>%
  group_by(employer_state) %>%
  summarize(n = n())

state_number$hover <- with(state_number, paste("State", employer_state, "<br>", "Number", n))

g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

map_1 <- plot_geo(state_number, locationmode = 'USA-states') %>%
  add_trace(
    z = ~n, text = ~hover, locations = ~employer_state,
    color = ~n, colors = 'Purples'
  ) %>%
  colorbar(title = "H1b Case Number") %>%
  layout(
    title = '2018 US H1b by State',
    geo = g
  )

map_1
```

## A map showing number of H1b in worksite state

```{r}
state_ws = 
  h1b_2018 %>%
  group_by(worksite_state) %>%
  summarize(n = n())

state_ws$hover <- with(state_ws, paste("State", worksite_state, "<br>", "Number", n))

g2 <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

map_2 <- plot_geo(state_ws, locationmode = 'USA-states') %>%
  add_trace(
    z = ~n, text = ~hover, locations = ~worksite_state,
    color = ~n, colors = 'Greens'
  ) %>%
  colorbar(title = "H1b Case Number") %>%
  layout(
    title = '2018 US H1b by worksite State',
    geo = g2
  )

map_2
```

## A graph showing top 10 cities with H1b cases in California state (worksite)

```{r}
city_ca = 
  h1b_2018 %>%
  filter(worksite_state == 'CA') %>% 
  group_by(worksite_city) %>%
  summarize(n = n()) %>% 
  filter(min_rank(desc(n)) <= 10)

city_ca %>% 
  mutate(worksite_city = fct_reorder(worksite_city, n)) %>% 
  plot_ly(x = ~worksite_city, y = ~n, color = ~worksite_city, type = "bar")
```


